### ISSUE TITLE
IRMA configuration

### ISSUE THREAD

**Issue by Albertperlas** [GSTT-CIDR/influenza_r9.4.1_rbk_2022#1]
Hi, 

I would like to ask you about your IRMA configuration: FLU-minion-final. Can you specify a bit more about this? How have you modified the FLU-minion configuration? 

Thanks, 
Albert Perlas

**Comment by TGSWilliams** [comment]
Hi, 

This is detailed in the supplementary methods:

“Consensus generation and control analysis
The FLU-minion config file was adapted as follows: the MIN_CONS_SUPPORT parameter was set to 20 to provide a consensus base call with a read depth of 20, MIN_AMBIG set to 0.5 to prevent mixed base calls, and ASSEM_PROG set to MINIMAP2.”

Thanks
